# Generated by Django 5.1.3 on 2024-12-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.IntegerField(verbose_name='Account No.')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('bal', models.FloatField(verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lacno', models.IntegerField(unique=True, verbose_name='Loan Account No.')),
                ('lamt', models.FloatField(verbose_name='Loan Amount')),
                ('acno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account')),
            ],
        ),
    ]
