# Generated by Django 5.1.3 on 2024-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.CharField(max_length=10, verbose_name='Emp No.')),
                ('ename', models.CharField(max_length=100, verbose_name='Emp Name')),
                ('esal', models.FloatField(verbose_name='Emp Salary')),
                ('ecity', models.CharField(max_length=50, verbose_name='Emp City')),
            ],
        ),
    ]
